### ISSUE TITLE
logic outs

### ISSUE THREAD

**Issue by envelopegen** [Strum/Strums_Mental_VCV_Modules#19]
should they attenuate?
![screen shot 2017-11-09 at 11 46 20 pm](https://user-images.githubusercontent.com/33540835/32648164-78575d5c-c5a9-11e7-8941-4e2547d53475.png)

**Comment by Strum** [comment]
Yes i've noticed the 1 volt output is not enough to trigger some module, i've changed some of the logic modules to output 5 instead but had forgotten about the clock divider.

on my list of fixes for next week, i'm busy this weekend.

**Comment by envelopegen** [comment]
thanks for the reply! really enjoying your pack! the clkdiv outputs 5v consistently... the logic module seems to be the issue... sorry i didn't make that clear in my screen shot.... nervous to ask, wasn't sure if you had built this just to work with your other modules with logic inputs. no rush thanks for all the work!
![screen shot 2017-11-10 at 6 26 15 pm](https://user-images.githubusercontent.com/33540835/32685396-ecf6c544-c644-11e7-8f78-5a12d42fde92.png)

**Comment by Strum** [comment]
Thanks, I had assumed that any positive signal would be enough to trigger other modules but it turns out that is not the case, I've changed the output of the logic module to 5v but you will have to build it from the latest source against the dev version of rack to get that functionality.

I'll check through the other modules for the same issue when I do bug fixes next week.,
