### ISSUE TITLE
Windows binaries please!

### ISSUE THREAD

**Issue by synthi** [Strum/Strums_Mental_VCV_Modules#2]

**Comment by Strum** [comment]
Sorry, the code only works with the development version at the moment, 

When 0.4.0 is released I will release it as a binary plugin package, until then you'll have to download the sources for Rack and compile them yourself. It's not hard, the README for Rack has simple clear instructions on how to do it and it take about 20 mins, most of which is waiting for the dependencies to build.

The development version has some nice new features that are not in the release version yet as well btw so that's a good reason to compile from source yourself as well.

**Comment by synthi** [comment]
0.4.0 is already released! :)

**Comment by Strum** [comment]
oh, i hadn't realised as i have been using the dev version.

I'll see if i can work out how to make a plugin.dll that works with the release version in the next few days.

**Comment by Strum** [comment]
Here it is, Enjoy!
https://github.com/Strum/Strums_Mental_VCV_Modules/blob/master/Releases/Windows/StrumsMentalModules.zip
