### ISSUE TITLE
Rendering issues in 1.0.x?

### ISSUE THREAD

**Issue by cschol** [Strum/Strums_Mental_VCV_Modules#56]
The LFO looks different in 1.0 than it did in 0.6. For example, the backgrounds of the faders are missing in 1.0.

v0.6.x:
![image](https://user-images.githubusercontent.com/624427/77234619-7d8d9d80-6b75-11ea-8201-7f5491650c75.png)

v1.0.x:
![image](https://user-images.githubusercontent.com/624427/77234576-0fe17180-6b75-11ea-97d1-6c04ac879170.png)

Is this a plugin rendering issue or did the module design change?

**Comment by neoh4x0r** [comment]
Seems to be by-design: https://github.com/Strum/Strums_Mental_VCV_Modules/blob/master/src/MentalQuadLFO.cpp#L266
https://github.com/VCVRack/Rack/blob/a5fc58910bcdfdd6babd77bafad7bbe142ac939a/include/componentlibrary.hpp#L531

It's just the green slider -- with no background shading.

It might be nice to have the background shading on there -- because the initial position of the sliders (at 0) is the bottom on slider bank and there is a lot of distance between the green leds and the sliders

There is another issue #5 asking for help with making some modules (if not all) look better.
Towards the bottom there was @Anthony-Lockwood who changed the background of the quad lfo and added a black-rectangle behind the sliders to make them easier to see.

In all honestly, those elements are stored in the svg resources -- inkscape is great tool for editing them.
